train:
  batch_size: 2
  seed: 2025
  epochs: 3000
  num_workers: 8
  restore_path: False
  save_path: None
  log_interval: 100
  lr: 0.0001
  factor: 0.9
  patience: 30
  min_lr: 0.000001
  energy_weight: 1
  force_weight: 99
  swa_energy_weight: 10
  swa_force_weight: 99
  momentum_weight: 100
  weight_decay: 1e-16
  kcal2mev: 43.36454
  calculate_electric: False
  has_charge: False
  charge_weight: 10
  edge_weight: 100

test:
  test_interval: 1
  test_batch_size: 32


data:
  base_path: null
  molecule: razobenzene
  num_train: 950
  num_val: 50
  num_test: null


model:
  name: LiTEN
  num_layers: 6
  num_heads: 8
  hidden_channels: 256
  num_rbf: 32
  cutoff: 5.0
  max_neighbors: 32
  max_z: 100
  vec_norm: False






